[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz_runs = 2048
solc_version = '0.8.15'
optimizer_runs = 1_000_000
optimizer = true
remappings = [
    'ERC721A/=lib/ERC721A/contracts/',
    'chainlink/=lib/chainlink/',
    'ds-test/=lib/solmate/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'hot-chain-svg/=lib/hot-chain-svg/contracts/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'solmate/=lib/solmate/src/',
    'utility-contracts/=lib/utility-contracts/src/',
    'bound-layerable=src/'
]


[fuzz]
runs = 4096

[profile.ir]
via_ir = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
