[default]
src = 'src'
out = 'out'
libs = ['lib']
fuzz_runs = 1000
solc_version = '0.8.15'
optimizer_runs = 1_000_000
optimizer = true
# via_ir = true
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
remappings = [
    "bound-layerable/=src/",
    "bound-layerable-test/=test/",
    "chainlink/=lib/chainlink/contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/"
]

[ir]
via_ir = true